### ISSUE TITLE
Uvoz tabele iz html

### ISSUE THREAD

**Issue by nejclu** [nejclu/APPR-2018-19#1]
link <- "https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)"
stran <- html_session(link) %>% read_html()
tabela_prir <- stran %>% html_nodes(xpath="//table[@class='wikitable sortable plainrowheaders']") %>%
  .[[1]] %>% html_table() %>% transmute(Država=`Country or area` %>% strapplyc("^([^[]*)") %>% unlist(),
                                        Prirast=`Change` %>%
                                          parse_number(locale=locale(grouping_mark=",")))

Zanima me, kako uvoziti tabelo, da bi bil pri podatku za prirast (change) poleg števila tudi "+" oz. "-", tako kot je to na spletni strani.
Poleg tega me zanima tudi, če so imena stolpcev in vrstic tabel lahko v angleščini ali morajo biti nujno v slovenščini.

Za odgovor se že vnaprej zahvaljujem.

**Comment by jaanos** [comment]
To, da se ne prikaže `+` pred pozitivnimi vrednostmi, naj te ne skrbi. Pomembno je namreč, da imaš podatke uvožene kot števila - če bi jih rad prikazal v tabeli, takrat poskrbiš za oblikovanje. 

Sicer pa, če boš imel podatke samo za eno leto, je smiselno, da imaš prebivalstvo in prirast v isti razpredelnici, vsako v svojem stolpcu (saj gre za različni lestvici). Če bi se pa odločil uvoziti prebivalstvo za obe leti, pa prirasta ne uvažaj, saj bi ga lahko potem izpeljal iz ostalih podatkov. 

Kar se imen stolpcev tiče, je načeloma vseeno - bi pa odsvetoval, da vsebujejo presledke in šumnike (ter ostale posebne znake). Tudi tukaj velja, da za lep izgled poskrbiš šele pri prikazovanju podatkov (npr. pri grafu nastaviš oznake osi oz. naslov legende).

Še to: da v issueju lepo prikažeš kodo, naredi tako:

~~~
```R
koda
```
~~~

Oznaka `R` pomeni, da je koda v R-ju in se bo potem ustrezno pobarvala (po potrebi lahko seveda uporabiš tudi druge programske jezike). S klikom na *View* lahko pred objavo vidiš, kako bo ta izgledala.
