### ISSUE TITLE
Uvoz zemljevida

### ISSUE THREAD

**Issue by nejclu** [nejclu/APPR-2018-19#2]
```R
obcine <- uvozi.zemljevid("http://baza.fmf.uni-lj.si/OB.zip", "OB",
                          pot.zemljevida="OB", encoding="Windows-1250") %>% fortify()
```
Pozdravljeni,
zanima me, kako v R uvoziti zemljevid, ki ga imam že pobranega. Zgornje funkcije, ki smo jo uporabili pri vajah, ne znam "popraviti", tako da bi delovala tudi v mojem primeru. Zazipan zemljevid imam shranjen v mapi "vizualizacija" z imenom "Europe.rar" (SHP datoteka v njej se imenuje "Europe.SHP").

Hvala za odgovor

**Comment by jernejbanevec** [comment]
Zdravo!
Sama datoteka `Europe.rar` ni uporabna (lahko jo iz svojega repozitorija kar izbrišeš), saj funkcija `uvozi.zemljevid` sprejme le `.zip` datoteke. Same datoteke se ti tudi ne splača najprej uvoziti, saj če kot parameter `url` funkcije `uvozi.zemljevid` nastaviš pravilno pot do spletne datoteke, se ti bo ta, v kolikor ta datoteka na danem mestu še ne obstaja, prenesla sama. Zemljevid se ti bo prenesel na mesto, ki ga nastaviš pod parametrom `mapa`.

Napaka pa je tudi znotraj funkcije `uvozi.zemljevid`. Za več informacij kako popraviti funkcijo glej issue: https://github.com/JernejcicZan/APPR-2018-19/issues/1

Potem, ko odpraviš napako znotraj funkcije `uvozi.zemljevid` in to funkcijo poženeš bi koda za pravilen uvoz zemljevida Evrope izgledala nekako tako:
```R
zemljevid <- uvozi.zemljevid("http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_countries.zip",
                             "ne_50m_admin_0_countries", mapa = "zemljevidi", pot.zemljevida = "", encoding = "UTF-8") %>% 
  fortify() %>% 
  filter(CONTINENT == "Europe" | SOVEREIGNT %in% c("Turkey", "Cyprus"), 
         long < 45 & long > -45 & lat > 30 & lat < 75)
```
Tukaj ti bo v isti mapi kot imaš working directory naredilo novo mapo imenovano `zemljevidi`. Parametre lahko seveda tudi sam malo spremeniš.

Opažam pa tudi, da v kodi `uvoz.r` spreminjaš t.i. `working directory`. Tega raje ne počni in to popravi tako, da pri uvozu datotek `2015_changed.csv`,  `2016_changed.csv` in `2017_changed.csv` spremeniš pot, da ti `R` sam pogleda znotraj mape `podatki`, npr.:
```R
tabela_2015 <- read_csv("podatki/2015_changed.csv", locale=locale(encoding="Windows-1250"))
```
