### ISSUE TITLE
Uvoz iz html-ja

### ISSUE THREAD

**Issue by nejclu** [nejclu/APPR-2018-19#3]
Živjo,
ponovno imam vprašanje glede uvoza tabele iz Wikipedie (povezava: https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations) )

Za zdaj moja koda izgleda tako:
```R
link <- "https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)"
stran <- html_session(link) %>% read_html()
tabela_preb <- stran %>% html_nodes(xpath="//table[@class='wikitable sortable plainrowheaders']") %>%
  .[[1]] %>% html_table() %>% transmute(Country=`Country or area` %>% strapplyc("^([^[]*)") %>% unlist(),
                                        prebivalstvo=`Population(1 July 2017)[3]` %>%
                                          parse_number(locale=locale(grouping_mark=",")))
```
Pri prirastu (Change) imam sedaj v stolpcu za vsako državo podano pozitivno vrednost, rad pa bi, da bi se pri državah, kjer je prirast negativen, izpisala negativna vrednost, tako kot je v tabeli na spletni strani.

Hvala za odgovor

**Comment by jernejbanevec** [comment]
Če prav razumem je problem pri uvozu tabele `tabela_prir` in ne tabele `tabela_preb`, sej le v prvi tabeli shraniš tudi stolpec `Change`.
Lahko shraniš kot vektor kot `character`, vendar bodi pozoren, saj potem z vrednostmi tega stolpca ne boš mogel računati. To lahko storiš tako da namesto `parse_number()` pokličeš funkcijo `parse_character()` in potem tvoja funkcija izgleda nekako tako:

```R
tabela_prir <- stran %>% html_nodes(xpath="//table[@class='wikitable sortable plainrowheaders']") %>%
  .[[1]] %>% html_table() %>% transmute(Country=`Country or area` %>% strapplyc("^([^[]*)") %>% unlist(),
                                        Change=`Change` %>%
                                          parse_character())
```
A to potem reši tvoj problem?

**Comment by nejclu** [comment]
Ja, problem je bil pri tabeli ```tabela_prir```, ne pa pri ```tabela_preb```, sem napačno pregledal zadeve :)
Če prav razumem lahko ```+``` ali ```-``` pred vrednostjo ohranim le, če vrednost shranim kot ```character```? Je mogoče, da bi imel vrednosti shranjene kot števila, da bi potem lahko naprej računal z njimi? (Torej da bi se pred negativnimi ohranil minus)

Cilj je dobiti ven korelacijo med stopnjo sreče v državi in prirastom ljudi.

**Comment by jernejbanevec** [comment]
Aha, komaj sedaj pravilno razumem problem. Seveda je mogoče imeti tudi negativne številske vrednost znotraj vektorja. Sem se pa tudi sam obrnil na asistenta, ker ne najdem vzroka te napake.

**Comment by nejclu** [comment]
Ok, hvala :)

**Comment by jaanos** [comment]
Problem je v tem, da se na spletni strani za minus namesto običajnega `-` uporablja znak `−` iz Unicodovega bloka [matematičnih simbolov](http://www.fileformat.info/info/unicode/char/2212/index.htm). Najbolje bo, če pred pretvorbo s `parse_number` opraviš zamenjavo:
```R
tabela_prir <- stran %>% html_nodes(xpath="//table[@class='wikitable sortable plainrowheaders']") %>%
  .[[1]] %>% html_table() %>% transmute(Country=`Country or area` %>% strapplyc("^([^[]*)") %>% unlist(),
                                        Change=gsub("\u2212", "-", Change) %>%
                                          parse_number(locale=locale(grouping_mark=",")))
```

**Comment by nejclu** [comment]
Najlepša hvala obema, sedaj mi dela.
