### ISSUE TITLE
Kmeans

### ISSUE THREAD

**Issue by nejclu** [nejclu/APPR-2018-19#5]
Pozdravljeni,
imam težave pri operiranju s funkcijo "kmeans".  Pri barvanju zemljevida Evrope bi rad, da bi bili podatki razdeljeni na k (npr. 6) vrednosti, ker bi bil tako obarvan zemljevid bolj pregleden, saj bi bile države s podobnimi vrednostmi obarvane z istim odtenkom. Hotel sem dodati stolpec v tabelo "tabela_evropske", v katerem bi bila za vsako vrstico določena vrednost, ki predstavlja določeno skupino držav s podobnimi podatki. Uspelo mi je dodati stolpec, v katerem je za vsako državo določena številka grupe (torej od 1 do 6), ne pa vrednost grupe, ki bi jo rad prikazal na zemljevidu (Stolpec je zdaj iz tabele izbrisan).

Hvala

**Comment by jaanos** [comment]
Najprej naj opozorim, da bi bilo za razvrščanje podatkov bolje uporabiti več spremenljivk (če sem prav razumel, si uporabil le podatke iz `tabela_evropske`) - enodimenzionalne podatke lahko namreč enostavno prikažeš z barvno lestvico (tj., privzeti prikaz za zvezne spremenljivke), kjer se takoj vidi, katere države so bolj podobne.

Sklepam torej, da si razdelitev dobil nekako tako:
```R
k <- kmeans(tabela_evropske[-1], 6)
```
Če želiš dodati centre v razpredelnico, lahko potem narediš tako:
```R
tabela_evropske$center <- k$centers[k$cluster, ]
```
Naj opozorim, da tukaj ni bila uporabljena funkcija `scale`, saj pri enodimenzionalnih podatkih ni potrebna - dobljeni centri bodo tako na isti lestvici kot vhodni podatki. Če bi pa delal razvrščanje z več spremenljivkami, bi bilo `scale` nujno uporabiti (razen, če veš, da so vsi podatki na isti lestvici). Dobljene centre (sedaj imaš seveda več vrednosti za vsak center, tako da zgornji način dodajanja ne bi deloval) bi moral prevesti nazaj na originalno lestvico (množenje za standardni odklon in premik za povprečje), da bi bili primerljivi z vhodnimi podatki.

**Comment by nejclu** [comment]
Tako je, delal sem z enodimenzionalnimi podatki. Pri januarski predstavitvi sem imel narisan zemljevid, na katerem je bilo 40 odtenkov modre. Če sem prav razumel profesorja, je podal nasvet, da bi bilo teh barv manj, da bi bil zemljevid bolj pregleden in bi tako lahko lažje videl katere države so si med seboj podobne.
Uporabil sem kodo, ki ste jo napisali in zdaj se zemljevid obarva tako, kot sem si zastavil.
Najlepša hvala.
