### ISSUE TITLE
Poročilo

### ISSUE THREAD

**Issue by nejclu** [nejclu/APPR-2018-19#6]
Pozdravljeni,
pri vključevanju shiny-ja v poročilo imam problem. Shiny se mi v poročilu včasih prikazuje pravilno, včasih pa ne - namesto tega se v poročilu pojavi "Not found". Ne vem od česa bi bilo to odvisno, saj vmes nisem spreminjal ničesar.
(Edit: moja shiny aplikacija je v mapi "shiny2" in ne v mapi "shiny")

Poleg tega me še zanima, če mi pri projektu manjkajo še kakšne večje zadeve. Predvidevam, da je naloga že skoraj zaključena.

Hvala že vnaprej in lep pozdrav

**Comment by jaanos** [comment]
Pri meni deluje, prav tako na Binderju, tako da bom kar dodal povezavo na repozitorij za zagovore, z @alenFMF pa se lahko domeniš za termin zagovora, če se seveda še nisi.

Kar se tiče nedelovanja Shinyja, ne vidim očitnega razloga, zakaj bi prihajalo do težav. Lahko svetujem le, da poskusiš znova namestiti knjižnico `shiny`. @jernejbanevec, lahko morda pri sebi preveriš, ali prihaja do podobnih težav?

Drugih pripomb nimam - svetoval bi le, da v tabeli v Shiny aplikaciji izpustiš stolpec z imenom države, saj je to kar enako izbrani državi, polega tega pa je (vsaj pri meni) tabela zaradi tega širša od okvirčka, znotraj katerega jo prikazuješ.

**Comment by nejclu** [comment]
V tabeli v shiny-ju sem odstranil stolpec z imenom države, tako kot ste predlagali.
Shiny se mi v poročilu še vedno prikazuje precej naključno, upam da bo na zagovoru delovalo.

Še enkrat najlepša hvala za vso pomoč pri projektu in lep pozdrav.

**Comment by jaanos** [comment]
Sem posodobil povezavo. Če boš še kaj spreminjal, prosim javi, da jo znova posodobim.

**Comment by jernejbanevec** [comment]
To, da se ti v poročilu ko tega ponovno poženeš pokaže `Not fould` lahko spremeniš tako, da v
https://github.com/nejclu/APPR-2018-19/blob/6a549b92c1de4c84422bcf40353345982efac3d4/projekt.Rmd#L10
odstraniš zamik (tabulator) pred `runtime: shiny`, saj ti zaradi zamika R to obravnava kot del `output`-a. Tako se ti bo koda vedno znova pognala in te napake ne bo več.

Opomnil bi pa tudi, da lahko vse probleme (#1, #2, #3, #4 in #5), ki si jih že uspešno razrešil zapreš. To storiš s klikom na **Close issue** oziroma **Close and comment**, če obenem še kaj napišeš.

**Comment by MarvinHerzog** [comment]
Pozdravljen, prosil bi te še, da nekam na začetek *projekt.Rmd* dodaš naslednjo vrstico:
```Sys.setlocale("LC_ALL","Slovenian")```
Lahko jo dodaš kar na začetek `{r setup}` bloka. S to vrstico se izogneš encoding napakam na nekaterih sistemih, kjer se šumniki v imenih spremenljivk/stolpcev ne prevedejo pravilno. Npr. na mojem računalniku dobim napako pri klicu stolpca `država`:

```
Error in parse(file, keep.source = FALSE, srcfile = src, encoding = enc) : 
shiny2/server.R:11:40: unexpected input
10:     tabela_shiny_sub <- reactive({
11:       a <- tabela_shiny[tabela_shiny$DrÅ¾
```

**Comment by nejclu** [comment]
Živjo! 
Hvala @MarvinHerzog za komentar, sem dodal vrstico v poročilo. Upam, da nisem zgrešil položaja, kjer bi morala ta vrstica biti - nisem bil prepričan ali je dovolj, da je koda postavljena znotraj narekovajev pri "r setup", ali mora biti znotraj zavitih oklepajev. Upam, da sedaj deluje tudi pri vas.

**Comment by jaanos** [comment]
Je v redu tako - bom posodobil povezavo.

**Comment by nejclu** [comment]
Pozdravljeni,
projekt je zaključen in shranjen na github-u. Prosil bi, če lahko ponovno posodobite povezavo.

Najlepša hvala in lep pozdrav
